apiVersion: v1
kind: Service
metadata:
  labels:
    app: buoy-sre-api
  name: buoy-sre-api-svc
spec:
  ports:
    - name: buoy-sre-api
      port: 5000
      targetPort: 5000
  selector:
    app: buoy-sre-api
  type: NodePort
